name: Client Lib JS Release Workflow

on:
  workflow_call:
    inputs:
      release_type:
        description: 'Type of release (e.g., go, node)'
        required: true
        type: string
      target_branch:
        description: 'Target branch for the release'
        required: true
        type: string
      npm_package_name:
        description: 'Name of the npm package'
        required: true
        type: string
      npm_package_alt_name:
        description: 'Alternative npm package name (if any)'
        required: false
        type: string
        default: ''
      create_release_branch:
        description: 'Whether to create a release branch for patch version 0'
        required: false
        type: boolean
        default: true
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release_please:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: ${{ inputs.release_type }}
          target-branch: ${{ inputs.target_branch }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created == 'true' || steps.release.outputs.prs_created == 'true' }}
        with:
          fetch-depth: 0

      - if: ${{ steps.release.outputs }}
        id: versions
        run: |
          set -ex

          RELEASE_CANDIDATE=true
          NOT_RELEASE_CANDIDATE='${{ steps.release.outputs.release_created }}'
          if [ "$NOT_RELEASE_CANDIDATE" == "true" ]
          then
            RELEASE_CANDIDATE=false
          fi

          MAIN_RELEASE_VERSION=x
          RELEASE_VERSION=y

          if [ "$RELEASE_CANDIDATE" == "true" ]
          then
            MAIN_RELEASE_VERSION=$(node -e "console.log('${{ steps.release.outputs.pr && fromJSON(steps.release.outputs.pr).title }}'.split(' ').reverse().find(x => x.match(/[0-9]+[.][0-9]+[.][0-9]+/)))")
            RELEASE_VERSION=$MAIN_RELEASE_VERSION-rc.$(node -e "console.log('$(git describe --tags --exclude rc*)'.split('-')[1])")
            RELEASE_NAME="rc$RELEASE_VERSION"
          else
            MAIN_RELEASE_VERSION=${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
            RELEASE_VERSION="$MAIN_RELEASE_VERSION"
            RELEASE_NAME="v$RELEASE_VERSION"
          fi

          echo "MAIN_RELEASE_VERSION=${MAIN_RELEASE_VERSION}" >> "${GITHUB_ENV}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> "${GITHUB_ENV}"
          echo "RELEASE_CANDIDATE=${RELEASE_CANDIDATE}" >> "${GITHUB_ENV}"
          echo "RELEASE_NAME=${RELEASE_NAME}" >> "${GITHUB_ENV}"

          echo "MAIN_RELEASE_VERSION=${MAIN_RELEASE_VERSION}" >> "${GITHUB_OUTPUT}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> "${GITHUB_OUTPUT}"
          echo "RELEASE_CANDIDATE=${RELEASE_CANDIDATE}" >> "${GITHUB_OUTPUT}"
          echo "RELEASE_NAME=${RELEASE_NAME}" >> "${GITHUB_OUTPUT}"

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created == 'true' || steps.release.outputs.prs_created == 'true' }}
        with:
          node-version: 20

      - name: Build and publish packages
        if: ${{ steps.release.outputs.release_created == 'true' || steps.release.outputs.prs_created == 'true' }}
        run: |
          set -ex

          echo "export const version = '$RELEASE_VERSION'" > src/lib/version.ts

          npm ci
          npm run build

          for f in package.json package-lock.json
          do
            sed -i 's|"version": "0.0.0",|"version": "'"$RELEASE_VERSION"'",|g' "$f"
          done

          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > ~/.npmrc

          DIST_TAG=patched
          if [ "$RELEASE_CANDIDATE" == "true" ]
          then
            DIST_TAG=rc
          elif [ "$GITHUB_REF" == "refs/heads/main" ] || [ "$GITHUB_REF" == "refs/heads/master" ]
          then
            DIST_TAG=latest
          fi

          echo "Publishing ${{ inputs.npm_package_name }} now..."
          npm publish --provenance --tag "$DIST_TAG"

          if [ -n "${{ inputs.npm_package_alt_name }}" ]
          then
            echo "Publishing ${{ inputs.npm_package_alt_name }} now..."
            for f in package.json package-lock.json
            do
              sed -i 's|\("name":[[:space:]]*"@supabase/\)'"${{ inputs.npm_package_name }}"'|\1'"${{ inputs.npm_package_alt_name }}"'|g' "$f"
            done
            npm publish --provenance --tag "$DIST_TAG"
          fi

      - name: Create GitHub release and branches
        if: ${{ steps.release.outputs.release_created == 'true' || steps.release.outputs.prs_created == 'true' }}
        run: |
          set -ex

          if [ "$RELEASE_CANDIDATE" == "true" ]
          then
            PR_NUMBER='${{ steps.release.outputs.pr && fromJSON(steps.release.outputs.pr).number }}'

            GH_TOKEN='${{ github.token }}' gh release \
              create $RELEASE_NAME \
              --title "v$RELEASE_VERSION" \
              --prerelease \
              -n "This is a release candidate. See release-please PR #$PR_NUMBER for context."

            GH_TOKEN='${{ github.token }}' gh pr comment "$PR_NUMBER" \
              -b "Release candidate [v$RELEASE_VERSION](https://github.com/${{ github.repository }}/releases/tag/$RELEASE_NAME) published."
          else
            if [ "$GITHUB_REF" == "refs/heads/main" ] || [ "$GITHUB_REF" == "refs/heads/master" ]
            then
              IS_PATCH_ZERO=$(node -e "console.log('$RELEASE_VERSION'.endsWith('.0'))")

              if [ "$IS_PATCH_ZERO" == "true" ] && [ "${{ inputs.create_release_branch }}" == "true" ]
              then
                GH_TOKEN='${{ github.token }}' gh api \
                  --method POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/${{ github.repository }}/git/refs \
                  -f "ref=refs/heads/release/${RELEASE_VERSION}" \
                  -f "sha=$GITHUB_SHA"
              fi
            fi
          fi 